import 'package:flutter/material.dart';
const kBgcolor = Colors.white;
const kappBarBgcolor = Colors.white;
const kHeadBody1Color = Colors.black;
const kBody1Color = Colors.black;
const KbottomNavigationBarSelectedColorinprod = Colors.black;
const KbottomNavigationBarSelectedColorindev = Colors.red;
const KbottomNavigationBarUnSelectedColor = Colors.grey;
const KbuttonColor = Colors.black;
const KbuttonTextColor = Colors.white;